//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application_kyropatkina
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibraryGames
    {
        public int idLibrary { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> idGame { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
