//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application_kyropatkina
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wallet
    {
        public int idWallet { get; set; }
        public Nullable<int> idUSer { get; set; }
        public Nullable<decimal> Account { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
